using System;
using System.Collections.Generic;
using Gameplay.Magic.Abilities.Base.Config;
using Gameplay.Services.Activity.Base;
using Signals.Activities.Base;
using Signals.Activities.Boss;
using UnityEngine;
using UnityEngine.AddressableAssets;
using Random = UnityEngine.Random;

namespace Gameplay.Services.Boss.Config
{
    [CreateAssetMenu(menuName = "CreateConfig/" + nameof(BossActivityConfig),
        fileName = nameof(BossActivityConfig))]
    public class BossActivityConfig : ActivityConfig
    {
        public List<BossSection> sections = new();

        protected override IActivityRequest ConstructSignal() => new BossActivityRequest();

        [Serializable]
        public struct BossSection
        {
            public List<BossConfig> configs;
            public List<MagicAbilityConfig> abilities;
            public List<AssetReferenceGameObject> bossReferences;


            [Space, Header("AUTO GENERATION")] public bool autoGenerated;

            public int additionallyGeneratedCount;

            public float minInterval;
            public float maxInterval;

            public int minIntervalCount;
            public int maxIntervalCount;

            public BossSection(BossSection bossSection)
            {
                configs = new List<BossConfig>(bossSection.configs);
                abilities = bossSection.abilities;
                bossReferences = bossSection.bossReferences;
                autoGenerated = bossSection.autoGenerated;
                additionallyGeneratedCount = bossSection.additionallyGeneratedCount;
                minInterval = bossSection.minInterval;
                maxInterval = bossSection.maxInterval;
                minIntervalCount = bossSection.minIntervalCount;
                maxIntervalCount = bossSection.maxIntervalCount;
            }


            public void Generate()
            {
                if (!autoGenerated)
                    return;

                for (int i = 0; i < additionallyGeneratedCount; i++)
                {
                    var intervalCount = Random.Range(minIntervalCount, maxIntervalCount + 1);

                    var intervals = new List<BossConfig.AbilityInterval>();

                    for (int j = 0; j < intervalCount; j++)
                    {
                        var abilityConfig = abilities[Random.Range(0, abilities.Count)];

                        intervals.Add(new BossConfig.AbilityInterval()
                        {
                            beforeInterval = Random.Range(minInterval, maxInterval + 1),
                            abilityConfig = abilityConfig
                        });
                    }

                    var config = new BossConfig
                    {
                        abilityIntervals = intervals,
                        bossReference = bossReferences[Random.Range(0, bossReferences.Count)]
                    };

                    configs.Add(config);
                }
            }
        }

        [Serializable]
        public struct BossConfig
        {
            public AssetReferenceGameObject bossReference;
            public List<AbilityInterval> abilityIntervals;

            [Serializable]
            public struct AbilityInterval
            {
                public MagicAbilityConfig abilityConfig;
                public float beforeInterval;
            }
        }
    }
}